name: Wowza Streaming Engine My First Module 
services:
    wse:
        hostname: wse.docker
        image: wowza/wowza-streaming-engine:latest-trial
        environment:
            - WSE_LICENSE_KEY=$WSE_LICENSE_KEY
            - ADMIN_USER=admin
            - ADMIN_PASSWORD=password
            - IPWHITELIST=*
            - TRANSCODER=disabled #enabled | disabled | remove to not change
            - LOG_LEVEL=INFO #DEBUG INFO WARN ERROR
            - SIMU_LIVE=disabled
        volumes:
            - ./code/wse-plugin-my-first-plugin/build/libs:/usr/local/WowzaStreamingEngine/lib.addon
            - ./wse.addon/conf:/usr/local/WowzaStreamingEngine/conf.addon
        ports:
            - 80:80
            - 443:443
            - 554:554
            - 1935:1935
            - 8087:8087
            - 6970-6999:6970-6999/udp
            - 10000:10000/udp
            
    manager:
        hostname: wsem.docker
        image: wowza/wowza-streaming-engine-manager:latest
        environment:
            - LOG_LEVEL=WARN #DEBUG INFO WARN ERROR
            - WSE_HOST=http://wse.docker:8087
        ports:
            - 8088:8080
